apiVersion: v1
kind: PersistentVolume
metadata:
    name: mariadb-pv
    labels:
        type: local
spec:
    capacity:
        storage: 20Gi
    accessModes:
        - ReadWriteOnce
    storageClassName: manual
    hostPath:
        path: /Users/marcusthelin/Dev/education/kubernetes-test/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: mariadb-pvc
spec:
    storageClassName: manual
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 20Gi
