apiVersion: v1
kind: PersistentVolume
metadata:
    name: frontend-pv
    labels:
        type: local
        app: frontend-pv
spec:
    capacity:
        storage: 10Gi
    accessModes:
        - ReadWriteOnce
    storageClassName: manual
    hostPath:
        path: /Users/marcusthelin/Dev/education/kubernetes-test/src
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: frontend-pvc
spec:
    selector:
        matchLabels:
            app: frontend-pv
    storageClassName: manual
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 10Gi
